### PR TITLE
Lodash dependency upgraded to 4.0.0

### PR DESCRIPTION
**Pull request by aleksievelizhanin**

### CODE REVIEW

**Comment by raimohanska** [comment]
Okeydokey! Thanks!

**Comment by lautis** [comment]
This made lodash runtime dependency of Bacon, which wasn't previously the case and it isn't required in dist/Bacon.js.

**Comment by raimohanska** [comment]
OMG :)

**Comment by raimohanska** [comment]
Will clean that up. When migrating to @lautis's new ES6 module approach, we can do some more spring cleaning too. Grunt might deserve a retirement.

**Comment by lautis** [comment]
I'm already on it. Changing _.contains to _.include in readme/common.coffee does the trick.

**Comment by raimohanska** [comment]
Ha! I remove the lodash runtime dep. LOL at this:

```
➜  bacon.js git:(master) ✗ npm install
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
npm WARN deprecated lodash@0.9.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
```

Not just one but three different old versions of lodash :)

**Comment by raimohanska** [comment]
But yeah, go on, if you're already on it. I'll grab a beer.

**Comment by lautis** [comment]
As we have 109MB of development dependencies there must be some duplication.

**Pull request merged**
