### PR TITLE
Run browser tests in Browserstack 

### PR DESCRIPTION
**Pull request by lautis**
Since Testling isn't working ("Testling is currently not working. We're working to fix it!"), let's try BrowserStack.

TODO:

- [x] enable open source plan for BrowserStack
- [x] sane test triggering: run browser tests only once per push
- [x] preferably report success/failure with separate commit status in GitHub
- [x] fix old IE builds
- [x] replace Testling build matrix image with BrowserStack link

### CODE REVIEW

**Comment by lautis** [comment]
@raimohanska, can you add me (lautis@gmail.com) to Bacon.js BrowserStack team? I was told that Bacon already has open source plan enabled in BrowserStack.

**Comment by raimohanska** [comment]
Added you to the team!

**Comment by lautis** [comment]
The setup seems to work quite reliably for most browsers. IE9 didn't work on Browserstack, but testing locally with VirtualBox passed the suite.

My idea was to have a separate test suite for the browser tests. If there is any flakiness, at least the normal suite will stay green. To set up this, CodeShip seems like the best alternative, but that can only be done by repo admins.

@raimohanska, can you add Bacon.js to CodeShip and invite me there, or give me access to the project webhooks?

**Comment by raimohanska** [comment]
There you go! Now you should be able to setup webhooks!

**Comment by lautis** [comment]
Works! Although the system is quite opaque – you need to be added to the Codeship/Browserstack team to see the results. But there's something running browser tests automatically.

A more open alternative might to have a Heroku app running the browser builds and push logs to gists. Or a Travis-CI after_script that runs Browserstack builds.

**Comment by raimohanska** [comment]
So what's the status here? Need help?

**Comment by lautis** [comment]
The tests work and are run, but the process is very opaque. Logs require access to browserstack/codeship.

I hope to be able to find some time to implement a better way to run tests, but if someone wants to help, that'd be great. A separate (optional?) job in Travis CI build matrix could be a good first step, then later we can figure out the separate build status.

**Comment by lautis** [comment]
This seems to almost work. The commit status is updated to the merge commit (for PRs) [successfully](https://api.github.com/repos/baconjs/bacon.js/statuses/11fb49b33373b8493b8ea90cfb5f279368108899). I just need to figure out how to get the original commit SHA in Travis.

**Comment by lautis** [comment]
@raimohanska, could you review this?

**Comment by raimohanska** [comment]
Looks good! Tests are run on a bunch of different browsers on Browserstack, which is great. Let's ship it!

**Pull request merged**
