### PR TITLE
assemble.js : Split source into smaller pieces

### PR DESCRIPTION
**Pull request by phadej**
- Implements #512 
    - makes it possible to split huge source into small pieces
- Implements #311
    - first step to support builds with custom feature set

Notes:
- Output is to `src/Bacon.coffee` to reduce changes (tests etc.)

### CODE REVIEW

**Comment by raimohanska** [comment]
splendid!

**Comment by raimohanska** [comment]
Rebased into master!

**Comment by raimohanska** [comment]
I guess we need to work on the "output is into src/Bacon.coffee" part still

**Comment by phadej** [comment]
I can move the output to `dist/Bacon.coffee`, it's trivial sed (is it?).

**Comment by phadej** [comment]
Moved.

**Comment by phadej** [comment]
This is merged manually

**Comment by arian** [comment]
Why not commonjs modules? Or is the plan to use ES6 modules when there is a ES6 rewrite or something?

**Comment by phadej** [comment]
IMHO what we do, is gluing pieces of code together, not modularising. Many pieces are adding stuff to the prototypes (i.e. mutating stuff defining in other pieces), which isn't very *modular*. 

That's my reasoning. Dunno what @raimohanska thinks about :)

**Comment by raimohanska** [comment]
What @phadej said. No objections against using ES6 modules though, provided that the same functionality is achieved:

1. result usable as a single AMD or CommonJS morulde as well as directly using single <script> tag
2. can build customized subset
3. no performance degradation and/or bloating of result javascript bundle file

**Comment by raimohanska** [comment]
Personally I'm fine with assembly.js solution, being simple and flexible.

**Comment by arian** [comment]
Seems fair enough. I usually really like it if I can just npm install and require the things I need, without another build tool. 

Modules that modify some other object (or Bacon.prototype or something) isn't really nice indeed.

**Pull request closed without merging**
