### PR TITLE
export Bacon.isProperty(Observable)

### PR DESCRIPTION
**Pull request by semmel**
For their different behaviour (i.e. having a "current" value or not), downstream code needs to inspect the type of observable it is dealing with.

### CODE REVIEW

**Comment by raimohanska** [comment]
Sure, makes sense!

**Comment by raimohanska** [comment]
@semmel I'd like to make you a contributor on the Bacon.js NPM package as well so you could publish the next version on NPM. Do you have an npm username?

**Comment by raimohanska** [comment]
My apologies for being a very bad maintainer for year already - I'd be super happy if more active folks like you would take charge on this project.

**Comment by semmel** [comment]
@raimohanska 
Thanks for merging!
> @semmel I'd like to make you a contributor on the Bacon.js NPM package as well so you could publish the next version on NPM. Do you have an npm username?

It's semmel as well.

> My apologies for being a very bad maintainer for years already - I'd be super happy if more active folks like you would take charge on this project.

No need to apologise, it's all voluntary commitment. In that sense, I cannot promise much regarding maintenance. Perhaps some tweaks here and there — certainly I won't fight the intricacies of TypeScript if that comes up in an issue.

**Comment by raimohanska** [comment]
Invited you as an owner on NPM. Technically you can merge your own PRs as well I think - but having a second opinion and code review is often a good idea of course. I'll try to be more responsive towards issues and PRs even though I'm unlikely to resume a more active development role for Bacon.js.

**Pull request merged**
