### PR TITLE
update combineTemplate to use original objects given as values (#615)

### PR DESCRIPTION
**Pull request by ottopoika**
Fixes issue https://github.com/baconjs/bacon.js/issues/615

### CODE REVIEW

**Comment by ottopoika** [comment]
This was my first time to touch Bacon.js code so direct but constructive pointers will be appreciated :)

**Comment by raimohanska** [comment]
To me it looks like you're now always using the original template objects as values and you'll end up mutating them when new values are pushed through the template. You should add a test for "does not mutate the original template objects" to make sure this doesn't happen.

**Comment by ottopoika** [comment]
```coffeescript
it.only "doesn't mutate template objects", ->
    value = {key: fromArray([1, 2])}

    Bacon
      .combineTemplate(value)
      .slidingWindow(2, 2)
      .onValue ([first, second]) ->
        expect(first).to.not.equal(second)
```

Tried something like this but slidingWindow is undefined. What is the preferred way to write tests?

**Comment by raimohanska** [comment]
When tests are run separately, only the dependencies of the tested module are included in the build to ensure that the given module actually works with its declared deps. 

You can however declare extra dependencies in test files too, like this:

    # build-dependencies: slidingwindow

**Pull request closed without merging**
