### PR TITLE
lint json

### PR DESCRIPTION
**Pull request by nchaulet**
Lint json (bower.json and package.json) to prevent issue #582

### CODE REVIEW

**Comment by phadej** [comment]
It's validated with `bowerJson` in recent commit https://github.com/baconjs/bacon.js/commit/633edc694aafa09aa2575e74eb07b1c48acf9e0c

**Comment by nchaulet** [comment]
ok :)

**Comment by raimohanska** [comment]
Thanks very much for taking the time anyway. Do you think linting would be beneficial anyway? I guess it would make sure our files would be in alphabetical order etc...

**Comment by raimohanska** [comment]
The test validates that bower.json is 1) valid JSON 2) valid using bower-json validator

**Comment by nchaulet** [comment]
bower-json validate is a better solution, there is no benefits to use linting

**Comment by raimohanska** [comment]
alrighty then, thanks!

**Pull request closed without merging**
