### PR TITLE
Distribute aggregated ES6 module

### PR DESCRIPTION
**Pull request by semmel**
I'd like to discuss the things I've done here. It's not very elegant and more the brute force (speak: shell scripts) code.

Good things first:
- In another test step all existing unit tests are transpiled to use the new aggregated ES6 module `dist/Bacon.mjs`.
- ~~Those tests identified another issue in `src/topromise.ts`, where the TS compiler did generate ES6 code which breaks when invoked. (This again underlines that one **cannot blindly trust the TS compiler output**, and running tests on the dist files may always be necessary. Personally I find this really scary. - Didn't they always say, TS was compatible to JS?)~~ This was resolved in #773 .
- Unit tests all green 🍏 

Lacking much TypeScript or Chai knowledge and being new to ES6 modules, these bad things happened:
- Transpiling unit tests takes ages
- Transpiling to a directory inside the test sources may be not wise.
- In the preparation shell script I had to "fix" some import paths using a hammer, i.e. `sed`
- Cleanup shell script uses some scary `rm` instructions. (At least I did not `rm -rf` though.)
- I struggled with `Bluebird`'s and `zen-observable`'s module format when used as custom Promise constructor and "Standard ES Observable" (will there ever be such a thing? Still at proposal Stage 1, last presented July 2017 :-/ ) in the tests.

### CODE REVIEW

**Comment by raimohanska** [comment]
Great, the tests proved useful :)

I was thinking the other day that one could make a "proxy bacon" file somewhere which the test files used for importing Bacon. This way to switch between different bundles, you could just replace the proxy file with a one the imports a different bundle. 

Is transpiling the tests into ES6 really necessary. I was under the (totally untested) illusion that it would be sufficient to just point to a different bundle. And use a proxy bacon :)

**Comment by semmel** [comment]
> Is transpiling the tests into ES6 really necessary. I was under the (totally untested) illusion that it would be sufficient to just point to a different bundle. And use a proxy bacon :)

Yes, that way should be explored. For my defence I've never worked with TypeScript and just employed a brute force method.

So if we run the TS unit tests using the Bacon proxy who points to the ES6 bundle,
- Can TypeScript simply import that *untyped* ES6 library for the *typed* tests without complaining? 
- TS target needs to be proxied as well from ES3 to the same ES version `dist/Bacon.mjs` was targeted to. Because with ES3 TS would transpile everything down missing the point completely. Also ES3 had no failing tests, only showing when working completely in ES6.

If I did not miss anything important it seems doable, does it not?

**Comment by semmel** [comment]
As I suspected [TypeScript cannot import .mjs files](https://medium.com/@iamstan/typescript-es-modules-micheal-jackson-2040216be793). 

If I do it anyway renaming `dist/Bacon.mjs`-> `dist/Bacon.ts` just for the test and overriding some `tsconfig.json` stuff e.g.
```bash
NODE_PATH=$NODE_PATH:./node_modules;\
TS_NODE_COMPILER_OPTIONS='{"allowJs":true, "target":"ES2018","noImplicitAny":false, \
 "strict": false, "strictPropertyInitialization":false,"alwaysStrict":false}' \
mocha -r ts-node/register test/topromise.ts
```
I get hundreds of `Bacon.ts:5040:32 - error TS2339: Property 'off' does not exist on type` errors!

Perhaps I'd have to feed some `Bacon.d.ts` file the TypeScript compiler so that it swallows the ES6 module, however first attempts with a triple slash directive `/// <reference path="../baconjs/bacon.js" />` failed.

It seems I am entering the hacking domain again.

My problem is that the current `3.0.12` release contains a *faulty* `dist/Bacon.mjs`! That fix is long presented in the branch with the `src/toPromise.ts` refactoring. I'd like to ship that fix but I am unable to provide a failing test for the old implementation. 😢  Because - as said earlier - that error is compiled away when targeting ES5.

Should I create a PR with just `src/toPromise.ts` then?

**Comment by semmel** [comment]
This branch contains changes that are either
- in the meantime resolved (#773),
- concern generated distribution files,
- attempts for making TS unit tests on ES bundles which did not work out, 
- no longer useful for my purposes (`Symbol.toStringTag`)

**Pull request closed without merging**
