### PR TITLE
Distribute Bacon.js as ES6 module

### LINKED ISSUE #748: Provide Aggregated ES Module?
While it's easy to "import" `dist/Bacon.js` in a web page using an AMD loader or simply via `<script>` tag, there is no distribution file for importing as ES module:
`import * as Bacon from "../dist/.Bacon.mjs"` requires transpiling and bundling from the *original sources* - `npm install baconjs` is insufficient.
Could such an aggregated ES module file not be generated in `scripts/assemble.js` by rollup?
```javascript
import typescriptPlugin from 'rollup-plugin-typescript2';

const
  config = {
    input: './src/bacon.ts',
    output: {
      format: "esm",
      file: "./dist/Bacon.mjs"  // <-- or whatever name
    },
    plugins:[
      typescriptPlugin({
        typescript: require("typescript"),
        useTsconfigDeclarationDir: true
      })
    ]
  };
  export default config;
```

It would certainly help with "build-step free" development in the browser.

### PR DESCRIPTION
**Pull request by semmel**
fixes #748 
In the dist folder the files `Bacon.mjs` and `Bacon.min.mjs` are created.
Use from your application with 
```javascript
import * as Bacon from '../node_modules/baconjs/dist/Bacon.mjs';
```

###TODO:
1. Make (`browsertest`) tests use the `dist/Bacon.mjs` instead of separately tsified and bundled Bacon sources. (I have no idea how to exclude `Bacon` in the browserify bundling operation) Ideas?

2. Did the removed call of the base class constructor in `Bus` do anything useful? (Reason for removal is that this line could not be compiled to ES6, the JavaScript error is that constructors must always be called using 'new')

### CODE REVIEW

**Comment by raimohanska** [comment]
I guess the extra call in the Bus constructor was some leftover from a transition. Didn't seem useful at all. On the same note, I removed two of the three `bind` calls from the constructor as well.

I don't quite understand your point 1 yet :)

**Comment by raimohanska** [comment]
Do you mean you'd like the browser tests use the Bacon.mjs bundle instead of the current Bacon.js bundle? In any case it would be great to be able to run tests against different bundling options to make sure they work. At minimum there should be some "smoke test" that ensures that all resulting bundles are functional to some extent.

**Comment by raimohanska** [comment]
Pushed the code to the [distribute-esm](https://github.com/baconjs/bacon.js/tree/distribute-esm) branch. Added you to the bacon.js team as well.

**Comment by raimohanska** [comment]
Added a "smoke test" for the .mjs bundle and merged to master. Released 3.0.11

**Comment by semmel** [comment]
> Do you mean you'd like the browser tests use the Bacon.mjs bundle instead of the current Bacon.js bundle? In any case it would be great to be able to run tests against different bundling options to make sure they work.

Yes that's exactly what I meant.

 Just quick to explain: Surpisingly (for me) the generated ES6 module contained an error which the original sources and the tsified ES5 CommonJS module did not contain!

It was the above mentioned extra call to EventStream constructor in the Bus constructor. This is on the one hand no problem for TypeScript and on the other hand did get replaced in ES5 (which does not have class) to some function. But the ES6 module looks much like the TypeScript source (just without the types) and it raised an error like "constructors must always be called using 'new'".

However this error did only show up in my app (when instantiating new Bus) because the Baconjs unit test do not yet use the Bacon.mjs bundle.

I was really surprised to learn that rollup (or whoever) generates faulty ES6 code from harmless (non-faulty) TypeScript sources! That's why I think it's a good idea to 

>  to run tests against different bundling options to make sure they work.

I think it's possible by e.g. by updating the assert dependency. I will propose it with a PR then.

**Pull request merged**
