### PR TITLE
Fix #511

### LINKED ISSUE #511: Errors are swallowed when using fromPromise(A+ promise)
When in dev mode, it would be very useful to have a global, catch-all error handler since bacon swallow all errors. A tiny error in a map() somewhere downstream, and nothing happens, no stream is consumed, no error is thrown.

It could be used as follow:

```
if (process.env.dev)
  Bacon.onError = e -> console.error(e);
```

### PR DESCRIPTION
**Pull request by phadej**
Alternative to https://github.com/baconjs/bacon.js/pull/502

ES6 promise doesn't have `.done` AFAIK.

- [x] tests

### CODE REVIEW

**Comment by phadej** [comment]
Crap, I can't write any tests as the exceptions are thrown asynchronously.

**Comment by AlexGalays** [comment]
I think that's a good fix.

**Comment by phadej** [comment]
Ah I can't anyway. The exception is rethrown asynchronously, and I don't want to mock that too much. But I refactored promise tests as a bonus.

**Comment by phadej** [comment]
Mergeable again.

**Comment by raimohanska** [comment]
Merged #549 already

**Pull request closed without merging**
