### PR TITLE
Make onValue/onError/onEnd chainable

### PR DESCRIPTION
**Pull request by raimohanska**
Makes more sense to return the observable itself from these methods instead of returning an "unsubscribe" function. Now you can do

```
observable
  .onValue(something)
  .onError(somethingElse)
  .onEnd(somethingFinal)
```

### CODE REVIEW

**Comment by raimohanska** [comment]
This would go to version 2.0, of course, as it constitutes a breaking change to the API.

**Comment by raimohanska** [comment]
This suggestion got some considerable criticism from my colleagues. You can already do the same using the do* family of methods:

```js
observable
  .doAction(something)
  .doError(somethingElse)
  .onEnd(somethingFinal)
```

Also, it turns out that people are actually using the returned unsub function from `onValue`.

The most significant problem with the proposed way of chaining is with synchronous observables (Bacon.once and friends) where it simple doesn't work: the first on* handler will drain the source and the others won't be called. OTOH, I'm seriously considering to make these methods asynchronous in 2.0 to avoid the related issues.

**Comment by semmel** [comment]
Hi,
I've relied on Bacon for some time and just discovered that these changes are on the table.
> Also, it turns out that people are actually using the returned unsub function from onValue.

Yes it's useful for cleaning up and perhaps to avoid memory leaks.

Secondly I would point out that the new api
```javascript
observable
  .onValue(something)
  .onError(somethingElse)
  .onEnd(somethingFinal)
```
would now use "dot-chaining" *after* the computation is kicked off by `.onValue()`. Until now nothing is executed before there is a `.onValue()`, `.onEnd()`, `onError()` or `.subscribe()`. (*Laziness*) As I understand it everything "dot-chained" (e.g. `.map()`, `.filter()`, `.flatMap()`) is essentially function composition - but when `.onValue()` returns the observable that would change.

Maybe one Bacon could adopt the [run function ](https://github.com/rpominov/fun-task/blob/master/docs/api-reference.md#taskrunhandlers) from [Task](https://github.com/rpominov/fun-task)? It already has a few similarities with Bacon:
```javascript
// like Bacon.fromBinder
const task = Task.create((onSuccess, onFailure) => {
  // ...
  return () => {
    // cancellation logic
  }
})

// Essentially like Bacon.onValue
// The computation is executed every time we run the task
const cancel = task.run({
  success(result) {
    // success result goes here
  },
  failure(result) {
    // failure result goes here
  },
})

// If we cancel the task the cancellation logic from computation
// will be executed (if provided)
cancel()
```

**Comment by raimohanska** [comment]
@semmel this change was indeed left out of 2.0 and will probably be left out forever for the reasons you described.

Except in 2.0, streams never respond synchrnously so the "event already consumed when subscribing" issue should be gone now.

Version 2.0.0 was released yesterday, so please try it and tell me how it works!

**Pull request closed without merging**
