### PR TITLE
Bus end

### PR DESCRIPTION
**Pull request by phadej**
Includes commits from https://github.com/baconjs/bacon.js/pull/573

### CODE REVIEW

**Comment by raimohanska** [comment]
Hmm.. the "Bacon.Bus does not plug after end(), second variant" test is still failing.

**Comment by raimohanska** [comment]
To me it seems that the test is wrong:

```coffeescript
  it "does not plug after end(), second variant", ->
    failed = false
    busA = new Bacon.Bus()
    busB = new Bacon.Bus()
    busB.onValue(-> failed = true;)
    busB.plug(busA)
    busA.push('foo')
    busB.end()
    expect(failed).to.equal(false)
````

You plug busA before ending busB, so it's correct to pass the "foo" event through, right?

**Comment by phadej** [comment]
Ah seems, I swapped the lines when "cleaning up the mess".

**Comment by phadej** [comment]
Fixed.

**Pull request merged**
