### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by chriscalo**

### CODE REVIEW

**Comment by raimohanska** [comment]
Thanks! README.md is a generated file though...

**Comment by raimohanska** [comment]
See https://github.com/baconjs/bacon.js#contribute

**Comment by chriscalo** [comment]
Tried running `npm run readme` and got:

```sh
> baconjs@2.0.9 readme /Users/chriscalo/Projects/bacon.js
> coffee readme/readme.coffee

Undefined anchors: stream-onvalue
Undefined anchors: stream-onvalue
Undefined anchors: property-onvalue
```

Should I just edit `readme-src.coffee` instead and whenever the then build happens it will generate the change?

**Comment by raimohanska** [comment]
Yeah, that's the way to do it

**Comment by chriscalo** [comment]
Thanks. I'll send a separate pull request with that change.

**Pull request closed without merging**
