### PR TITLE
flatMap*WithPriority

### PR DESCRIPTION
**Pull request by semmel**
*Disclaimer:* This PR just illustrates the problem and a very simple implementation + tests. Therefore the  description of the suggested new methods is missing, as well as the alias `.flatMapConcatWithPriority`.

The *problem*: I need the buffering behaviour of `.flatMapConcat` aka `flatMapWithConcurrencyLimit(1)` and this works just fine. The events entering `flatMapConcat` while the previously created stream has not ended, are queued. However I need certain queued events to be handled with priority. I could not figure an easy way to do this with existing methods like `Bacon.withStateMachine`. I don't even know if this is at all useful, or a *"reactive"* thing to do.

To do that I introduce a new `.flatMapWithConcurrencyLimitAndPriority` method which takes a comparison function (like that used by `Array.prototype.sort` - maybe not the most wise thing to do) which governs the sorting of the queued events in `.flatMap_`. The changes to `.flatMap_` are minimal because I use an unefficient and unperformant way to implement a *priority queue* in simply sorting the queue array on every push-back. There are far better [implementations for a priority queue in JS](https://github.com/wi-ski/FunctionalPriorityQueue). However BaconJS be better still dependency free I guess.

Now you can do for example:
```javascript
const
source = Bacon.fromArray([9, 8, 0, 6]),
output = source.flatMapWithConcurrencyLimitAndPriority(1, 
	R.subtract, number => Bacon.later(10, number)
);

output.reduce([], R.flip(R.append)) 
// -> [9, 0, 6, 8]
//      ^ 
// because at the time 9 enters flatMapWithC. there is no buffering yet and it is not
// subject to sorting.
```

What do you think?

### CODE REVIEW

**Comment by raimohanska** [comment]
Makes sense to me. Just a thought: in the typescript branch, this would be easier to incorporate as the queue prioritization function could be just another param to `flatMapWithConcurrencyLimit` and no extra method would be needed. This is possible because the https://github.com/baconjs/bacon.js/#function-construction-rules are no longer there. 

Would you like to try mounting this new functionality into the new branch instead? We might come out with a 3.0-alpha-1 version without much delay I guess.

**Comment by semmel** [comment]
Okay I'll try to commit into the 3.0 branch next weekend.

**Comment by semmel** [comment]
Hmm. I just figured out, that for my problem it is better to expose an externally managed priority queue in a separate Property. It is not that the implementation has failed, but with my proposed implicit priority queue, *the flow of events was too opaque*. I think I was trying to push too much business logic into the Bacon stream library. Also I might have created circular streams and the results were unpredictable.

I refactored my module with the effect, that I do no longer need the priority queue in `Bacon.flatMapConcat`. So I would not pursue this PR for now. You may feel free to close it now.

Regards
Semmel

**Comment by raimohanska** [comment]
Ah okay then, thanks for letting me know!

**Pull request closed without merging**
