### PR TITLE
Bacon.fromEvent custom binder

### PR DESCRIPTION
**Pull request by steve-taylor**

### CODE REVIEW

**Comment by steve-taylor** [comment]
This supersedes #703.

**Comment by raimohanska** [comment]
This looks legit to me: it's more versatile than #703 with respect to parameters.

Comments?

**Comment by steve-taylor** [comment]
Rebased on the latest `master` commit.

**Comment by raimohanska** [comment]
Merged! Published 2.0.4. (some skipped minor versions to fix the version info strings in json and js files in the release bundle)

**Pull request merged**
