### PR TITLE
Bacon.fromEvent options

### PR DESCRIPTION
**Pull request by steve-taylor**
This adds support for providing the third argument to [`EventTarget.addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) via [`Bacon.fromEvent`](https://github.com/steve-taylor/bacon.js/blob/from-event-options/README.md#bacon-fromevent).

### CODE REVIEW

**Comment by raimohanska** [comment]
Maybe rename to bit-too-specific `listenerOptionsOrUseCapture` to `options` because `Bacon.fromEvent` is used for other event sources than DOM EventTargets. The added feature is agnostic to the content of the parameter, so the name should reflect that.

**Comment by raimohanska** [comment]
Maybe it should be just `...args` and support an unspecified number of arguments instead of a fixed single arg?

**Comment by darrennolan** [comment]
My thought on the name was options feels more bacon-y, rather than specify
it'll head to the listener.

**Comment by raimohanska** [comment]
Yeah options is a fine name, it's just that allowing multiple args might be more future-proof. Why limit to 1?

Not sure what you meant by "rather than specify it'll head to the listener". I'm not native in English :( In any case I think it's fair to say that this options/args will be passed directly to the event source, instead of using the anyhow within Bacon.

**Comment by steve-taylor** [comment]
If we make it more generic (not making any assumptions as to the signature of subscribe/unsubscribe methods), how does `Bacon.fromEvent` know whether the the last parameter is a listener subscribe/unsubscribe parameter or `eventTransformer`?

Maybe we should consider something like this instead:

```js
Bacon.fromEvent(
    (listener) => window.addEventListener('scroll', {passive: true}, listener),
    (listener) => window.addEventListener('scroll', {passive: true}, listener),
    () => window.scrollX
);
```

It’s flexible and there’s no ambiguity because the first two parameters are functions instead of an object and a string. Or this could be a new function, although I can’t think of a good name.

**Comment by raimohanska** [comment]
B.fromBinder does already what you described. The name sucks tho :(

-juha-

**Comment by raimohanska** [comment]
Also, the same ambiguity exists with the single param version too, right?

-juha-

**Comment by steve-taylor** [comment]
> B.fromBinder does already what you described.

It’s more verbose/ugly:

```js
Bacon.fromBinder((sink) => {
    const listener = () => void sink(window);

    window.addEventListener('scroll', listener, {passive: true});

    return () => void window.removeEventListener('scroll', listener, {passive: true});
});
```

**Comment by raimohanska** [comment]
Uglier, maybe so. More verbose, so-so. Not by a considerable margin at least. 

Anyways, the proposed change in the PR is definitely the nicest solution to this particular case:

```js
    Bacon.fromEvent(window, 'scroll', { passive: true })
```

.. so IMO that's definitely something to support regardless of any additional modifications. To return to the the single-arg vs multiple-args issue: the ambiguity regarding the last parameter `eventTransformer` exists in both cases with the consequence that function arguments cannot be supported, but that's not a problem with the presented use case, at least.

**Comment by raimohanska** [comment]
I suggest we limit the discussion in this PR to the original suggestion and open new PRs/Issues for further improvements. That ok?

**Comment by steve-taylor** [comment]
> Yeah options is a fine name

I'll rename it to `options`.

**Comment by steve-taylor** [comment]
Superseded by #710.

**Pull request closed without merging**
