### PR TITLE
ES Observable interoperability

### PR DESCRIPTION
**Pull request by lautis**
Implement interoperability adapter for [ES observable](https://tc39.github.io/proposal-observable/) via `Observable[Symbol.observable]` To allow consumption of ES observables in Bacon, there is `Bacon.fromESObservable` that accepts ES observables as arguments. This also handles RxJS 5.x Observables.

This does not make Bacon a full ES Observable implementation. That might not be an achievable or even a desirable goal. There are some missing methods in Bacon, but also some differences in semantics.

Implements #633.

### CODE REVIEW

**Comment by raimohanska** [comment]
I removed nodejs 0.10 from travis because it failed. No-one's using so old nodejs anyway, I hope.

**Comment by raimohanska** [comment]
This looks good to me. Any reason not to merge?

**Comment by lautis** [comment]
Nope, go ahead!

**Comment by raimohanska** [comment]
Oh, one more thing. README.

**Comment by lautis** [comment]
Added documentation. I had to create an alias for Observable[Symbol.observable] as the documentation generator didn't like the function signature. The alias is likely a good thing anyway.

**Pull request merged**
