### PR TITLE
Prevent errors from repeating in a debounced stream

### LINKED ISSUE #560: Error thrown in debounce stream never ends
When an error is thrown inside a debounced event stream, the error is continuously emitted.

This error occurs on the latest release but not in earlier releases. I narrowed down the breaking commit to 4794940.

Here's the code that reproduces the issue:

    Bacon.once(1).debounce(1000).onValue(function() {
        throw 'Error';
    });

In release 0.7.23 the output is:

> Uncaught Error

In release 0.7.50 the output is:

> Uncaught Error
> Uncaught Error
> Uncaught Error
> Uncaught Error
> Uncaught Error
> ...

PR with a fix will be submitted shortly.

### PR DESCRIPTION
**Pull request by kdeloach**
Partially reverts "Optimise Bacon.later, Bacon.never and Bacon.once"
479494056b492dd3b10b20a94fff716e866310f2

Fixes #560

### CODE REVIEW

**Comment by raimohanska** [comment]
Thanks for the find and the proposed fix. We still need a test case for this.

**Comment by raimohanska** [comment]
I thinks I have a better fix :) 

80661af9e9c1c1732e19c39f1873c399e4de7a94

It might indeed be best not to use `setInterval` for scheduling a single event.

**Comment by kdeloach** [comment]
Thanks, your solution is much better!

**Comment by raimohanska** [comment]
Thanks! I'm always happy when people come with PRs instead of just problems.

**Pull request closed without merging**
