### PR TITLE
Use loose mode for spread operator implementation

### LINKED ISSUE #656: Usage of Array.from in bacon.js
The `bacon.js` file provided in `dist/` (and thus also in npm) makes use of `Array.from` which is not widely supported.

I guess this is something that can be configured during Coffeescript transpilation and it should be, because I was not able to use bacon in Safari 8 (which ships with every Mac Version older than El Capitan).

### PR DESCRIPTION
**Pull request by lautis**
Loose mode doesn’t require Array.from. This might have some compatibility edge cases, but the behaviour is same as for old CoffeeScript implementation.

Fixes #656.

### CODE REVIEW

**Comment by tonekk** [comment]
:+1:

**Comment by raimohanska** [comment]
Included this in release 0.7.83.

**Comment by raimohanska** [comment]
What's up with the codeship build btw? I have just observed that we have a new failing thingie :)

**Comment by lautis** [comment]
The Codeship build only works with #651. I've paused the builds so there shouldn't be errors. Let's enable the build when there's something in master.

**Pull request merged**
