### PR TITLE
observable.toPromise

### PR DESCRIPTION
**Pull request by phadej**
`npm install --save-dev when` sorted deps list :(

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
Are you sure we should implement a feature that is not crossbrowser? http://caniuse.com/#feat=promises
Our tests will fail on all the IE. Anyway I think it's also time to talk about dropping the support for the old IE ( at least 7 and 8 ) cc @raimohanska

**Comment by phadej** [comment]
The tests won't fail, because of es6-shim.

**Comment by GianlucaGuarini** [comment]
Ok but then it must be specified in the doc somewhere.

**Comment by phadej** [comment]
Amended the commit with notice about promise implementation.

**Comment by raimohanska** [comment]
This needs to be rebased

**Comment by phadej** [comment]
Rebased and transformed to JS now!

**Comment by raimohanska** [comment]
Looks good. The only thing I'm a bit worried 'bout is that RxJs toPromise resolves to the *last* value, not the first. I have no strong opinion on which would be the best way, but I'd prefer minimizing the confusion. 

What do you think @pozadi , @mattpodwysocki ? Should we resolve to the last or the first value of an Observable and why?

**Comment by phadej** [comment]
Hmm, maybe I make both, with `toPromise` resolving to the last, and `firstToPromise` to the first.

**Comment by pozadi** [comment]
I also don't have strong opinion on this, I like the idea of two methods.

But since you asked, I have another two things about this method that bother me :)

1. I think we should not resolve promise with `undefined` if there was no value/error. This will be indistinguishable from case when observable emits `undefined` value. I think we should left promise unresolved, and maybe `.toPropmise` should accept the `default` argument with witch promise will be resolved (rejected?) in case there is no value/error.

2. Maybe `.toPropmise` should accept the promise constructor as argument, and if it not provided use `windows.Promise`?

**Comment by phadej** [comment]
@pozadi I implemented *2.* as it was easy. 

Not sure about *1.* though. Either it will be `stream.toPromise(defaultValue, PromiseCtr)` or then user could do `stream.startsWith(defaultValue).toPromise(PromiseCtr)`. IMHO single parameter combinators are prettier, easier to reason about default values.

**Comment by pozadi** [comment]
How about options object as single argument?

```js
a.toPromise({default: 0}); // resolves with `0` if there was no value/error
a.toPromise({defaultError: 0}); // rejects with `0` if there was no value/error
a.toPromise({constructor: when.promise});
a.toPromise({constructor: when.promise, defaultError: 0});
```

**Comment by phadej** [comment]
@pozadi then it starts to be so complicated, I rather drop the whole combinator.

**Comment by pozadi** [comment]
Ok, how about leaving promise unresolved at least? :)

Users, can always do `stream.startsWith(defaultValue).toPromise()` if they want it to always be resolved.

**Comment by raimohanska** [comment]
Here's RxJs impl: https://github.com/Reactive-Extensions/RxJS/blob/47cbafa678c0e4f66c7307c8b8ecaab3407444fb/src/core/linq/observable/topromise.js

I kinda agree with it. It resolves only if there's a value at end.

The function also takes an optinal promise constructor param. Why not use the same semantics here?

**Comment by pozadi** [comment]
Yep, all the same things I'm suggesting, I probably looked at Rx's impl before and it stucked in my mind.

**Comment by raimohanska** [comment]
Would be a favor to the users if rx/bacon/kefir had the same toPromise semantics :)

**Comment by phadej** [comment]
Now it should work this way. As a bonus there is `first` and `last`.

**Comment by raimohanska** [comment]
Excellent!

**Comment by mattpodwysocki** [comment]
Why bother having a first or last when you can call take(1) or just let it run?

**Comment by raimohanska** [comment]
@mattpodwysocki not sure what you mean by "just let it run"?

First is, of course, equivalent to take(1).

**Comment by mattpodwysocki** [comment]
@raimohanska meaning let it run to the end and take the last value versus the first.  I think only one operator is needed here and it's up to the user to specify the first or last via take(1) or .last() or whatever...

**Comment by raimohanska** [comment]
Well yeah, both ways work fine for me.

**Pull request merged**
